version: '3'

services:
  dash:
    container_name: dash_app
    restart: always
    build:
      context: ./dash-nginx-uwsgi-docker
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8080:80"


  #  dash_app:
  #    container_name: dash_app
  #    restart: always
  #    build: 
  #      context: ./dockerfile
  #      dockerfile: dash
  #    ports:
  #      - "8000:8000"
  #    command: gunicorn -w 1 -b :8000 app:server
  #
  #
  #  nginx:
  #    container_name: nginx
  #    restart: always
  #    build: 
  #      context: ./dockerfile
  #      dockerfile: nginx
  #    ports:
  #      - "80:80"
  #    depends_on:
  #      - dash_app